# 01 · Scraping

Descarga desde iNaturalist a `Insectos/<especie>/` y registra la procedencia en `metadata.csv`. Incremental: deduplica por `photo_id`, así que reejecutar solo baja lo que falta.

Solo licencias abiertas. Quedan fuera las fotos sin licencia declarada y `cc-by-nc-nd`, cuyo ND prohíbe obras derivadas (recortar y aumentar)

In [5]:
import hashlib
import json
import re
import time

import requests

from corpus import (IMAGENES, LISTA_ESPECIES, MANIFIESTO, METADATA,
                    escribirCsv, leerCsv)

API = "https://api.inaturalist.org/v1"
LICENCIAS = "cc0,cc-by,cc-by-nc,cc-by-sa,cc-by-nc-sa"
LICENCIAS_OK = set(LICENCIAS.split(","))
PAUSA = 0.25          # entre descargas de fotos
PAUSA_API = 1.0       # entre llamadas a la API

RECONSTRUIR = True    # baja lo que registra metadata.csv; False construye uno nuevo

POR_ESPECIE = 350

COLUMNAS = ["especie", "taxon_id", "observation_id", "photo_id", "quality_grade",
            "licencia", "atribucion", "url", "archivo", "sha256"]

## Cliente

In [6]:
def pedir(sesion, ruta, params, intentos=5):
    """Reintenta con espera creciente ante 429 y cortes de red."""
    for intento in range(intentos):
        try:
            respuesta = sesion.get(f"{API}/{ruta}", params=params, timeout=30)
        except requests.RequestException as e:
            print(f"    {type(e).__name__}, reintento en {2 ** intento}s")
            time.sleep(2 ** intento)
            continue
        if respuesta.status_code == 429:
            espera = float(respuesta.headers.get("Retry-After", 2 ** intento))
            print(f"    429, esperando {espera:.0f}s")
            time.sleep(espera)
            continue
        respuesta.raise_for_status()
        return respuesta.json()
    raise RuntimeError(f"{ruta} falló tras {intentos} intentos")


def nombreCorto(entrada):
    limpio = re.sub(r"\(.*?\)|,.*$", "", entrada)
    return " ".join(limpio.split()[:2])


def carpetaDe(nombre):
    return nombre.lower().replace(" ", "_")


def buscarTaxon(sesion, nombre):
    resultados = pedir(sesion, "taxa", {"q": nombre, "rank": "species",
                                        "per_page": 1, "is_active": "true"})["results"]
    return resultados[0] if resultados else None


def disponibilidad(sesion, taxonId):
    """Techo real de una especie, para saber si subir el tope sirve de algo."""
    return pedir(sesion, "observations", {
        "taxon_id": taxonId, "quality_grade": "research", "photos": "true",
        "photo_license": LICENCIAS, "per_page": 1,
    })["total_results"]


def descargar(sesion, url, destino):
    respuesta = sesion.get(url, timeout=45)
    respuesta.raise_for_status()
    destino.write_bytes(respuesta.content)
    return hashlib.sha256(respuesta.content).hexdigest()

## Paginación

In [7]:
def fotosDe(sesion, taxonId, maximo):
    vistas, pagina = set(), 1
    while len(vistas) < maximo:
        filtros = {"taxon_id": taxonId, "photos": "true", "photo_license": LICENCIAS,
                   "quality_grade": "research", "order_by": "id", "order": "asc",
                   "per_page": 200, "page": pagina}

        observaciones = pedir(sesion, "observations", filtros)["results"]
        if not observaciones:
            return
        for observacion in observaciones:
            for foto in observacion["photos"]:
                # el filtro del servidor es por observación: una válida arrastra
                # sus otras fotos, que pueden ser ND
                if foto["id"] in vistas or foto.get("license_code") not in LICENCIAS_OK:
                    continue
                vistas.add(foto["id"])
                yield observacion["id"], observacion.get("quality_grade", ""), foto
                if len(vistas) >= maximo:
                    return
        pagina += 1

## Descarga

Acumula sobre `metadata.csv` y lo reescribe entero al final

## Reconstruir el corpus publicado

`metadata.csv` guarda la URL y el `sha256` de cada foto, así que el corpus se reconstruye exactamente. Volver a consultar la API traería un conjunto distinto, porque iNaturalist gana observaciones nuevas y pierde otras, y el reparto congelado en `manifiesto.json` dejaría de corresponder.

Reejecutar es seguro: salta lo que ya está en disco.

In [8]:
if RECONSTRUIR:
    sesion = requests.Session()
    sesion.headers["User-Agent"] = "butterfly-dataset/1.0"

    # metadata.csv acumula 154 especies de la exploración inicial; el corpus son
    # las 100 del manifiesto, y bajar las demás serían 13 000 fotos inservibles
    delCorpus = set(json.loads(MANIFIESTO.read_text())["reparto"])
    filas = [f for f in leerCsv(METADATA) if f["especie"] in delCorpus]
    pendientes = [(f, IMAGENES / f["especie"] / f["archivo"]) for f in filas
                  if not (IMAGENES / f["especie"] / f["archivo"]).exists()]
    print(f"{len(filas):,} fotos del corpus · {len(pendientes):,} por descargar")

    caidas, alteradas = [], []
    for numero, (fila, destino) in enumerate(pendientes, start=1):
        destino.parent.mkdir(parents=True, exist_ok=True)
        try:
            sha = descargar(sesion, fila["url"], destino)
        except requests.RequestException as error:
            destino.unlink(missing_ok=True)
            caidas.append(f'{fila["archivo"]}: {str(error)[:60]}')
        else:
            if sha != fila["sha256"]:
                alteradas.append(fila["archivo"])
        if numero % 500 == 0:
            print(f"  {numero:,}/{len(pendientes):,}")
        time.sleep(PAUSA)

    print(f"\ncaídas {len(caidas)} · con sha256 distinto al registrado {len(alteradas)}")
    for linea in (caidas[:3] + alteradas[:3]):
        print(f"  {linea}")

34,901 fotos del corpus · 36 por descargar

caídas 0 · con sha256 distinto al registrado 0

In [9]:
if not RECONSTRUIR:
    especies = json.loads(LISTA_ESPECIES.read_text())["species"]
    especies = [e for e in especies if "sp." not in e["name"]]

    sesion = requests.Session()
    sesion.headers["User-Agent"] = "butterfly-dataset/1.0"

    filas = leerCsv(METADATA)
    caidas = []
    conocidas = {fila["photo_id"] for fila in filas}
    print(f"{len(filas)} fotos ya registradas · {len(especies)} especies a recorrer")

    for numero, entrada in enumerate(especies, start=1):
        nombre = nombreCorto(entrada["name"])
        taxonId = entrada.get("taxon_id")
        if taxonId is None:
            taxon = buscarTaxon(sesion, nombre)
            time.sleep(PAUSA)
            if taxon is None:
                print(f"[{numero}/{len(especies)}] {nombre}: sin taxón")
                continue
            taxonId = taxon["id"]

        carpeta = IMAGENES / carpetaDe(nombre)
        carpeta.mkdir(parents=True, exist_ok=True)
        nuevas = 0
        for observacionId, grado, foto in fotosDe(sesion, taxonId, POR_ESPECIE):
            url = foto["url"].replace("square", "large")
            archivo = carpeta / f"{carpetaDe(nombre)}_{foto['id']}.jpg"
            if str(foto["id"]) in conocidas and archivo.exists():
                continue
            try:
                sha = descargar(sesion, url, archivo)
            except requests.RequestException as e:   # una foto caída no debe abortar la corrida
                caidas.append({"archivo": archivo.name, "url": url, "error": str(e)[:80]})
                time.sleep(PAUSA)
                continue
            filas.append({
                "especie": carpetaDe(nombre), "taxon_id": taxonId,
                "observation_id": observacionId, "photo_id": foto["id"],
                "quality_grade": grado, "licencia": foto["license_code"],
                "atribucion": foto.get("attribution", ""), "url": url,
                "archivo": archivo.name, "sha256": sha,
            })
            nuevas += 1
            time.sleep(PAUSA)

        filas = list({f["photo_id"]: f for f in filas}.values())
        escribirCsv(METADATA, filas, COLUMNAS)   # por especie: interrumpir no deja imágenes sin procedencia
        print(f"[{numero}/{len(especies)}] {nombre}: +{nuevas}")

    print(f"\n{len(filas)} fotos en metadata.csv · {len(caidas)} descargas fallidas")

## Inventario

In [10]:
import pandas as pd

enDisco = {(carpeta.name, foto.name)
           for carpeta in IMAGENES.iterdir() if carpeta.is_dir()
           for foto in carpeta.glob("*.jpg")}

meta = pd.DataFrame(filas).drop_duplicates("photo_id")
meta = meta[[(e, a) in enDisco for e, a in zip(meta.especie, meta.archivo)]]
porEspecie = meta.groupby("especie").agg(fotos=("photo_id", "size"),
                                         observaciones=("observation_id", "nunique"))
print(f"{len(porEspecie)} especies · {porEspecie.fotos.sum():,} fotos")
print(f"por especie: min {porEspecie.fotos.min()}, mediana "
      f"{porEspecie.fotos.median():.0f}, max {porEspecie.fotos.max()}")
porEspecie.sort_values("fotos").head(10)

# metadata.csv acumula entre corridas y nunca poda: un rescrapeo añade los ids
# nuevos y conserva los viejos, así que puede describir más fotos de las que el
# pipeline usó. Si esto no da cero, hay que podarlo contra auditoria.csv.
sobrantes = len(filas) - len(enDisco & {(f["especie"], f["archivo"]) for f in filas})
print(f"filas sin archivo en disco: {sobrantes}")

100 especies · 34,901 fotos
por especie: min 287, mediana 350, max 439

                    fotos  observaciones
especie
epargyreus_cruza      287            158
eueides_procula       304            191
mesosemia_mevania     315            186
actinote_neleus       329            203
caligo_eurilochus     332            211
taygetis_mermeria     338            256
dione_moneta          349            208
marpesia_marcella     350            218
marpesia_berania      350            223
manataria_maculata    350            246

## Cuánto más hay disponible

En caso de necesitar mas data por especie

In [11]:
techos = {}
for especie, fila in porEspecie.iterrows():
    taxon = meta[meta.especie == especie].taxon_id.iloc[0]
    techos[especie] = disponibilidad(sesion, int(taxon))
    time.sleep(PAUSA_API)

porEspecie["obs_disponibles"] = pd.Series(techos)
porEspecie["fotos_estimadas"] = (porEspecie.obs_disponibles
                                 * porEspecie.fotos / porEspecie.observaciones).round()
for tope in (200, 350, 500):
    n = (porEspecie.fotos_estimadas >= tope).sum()
    print(f"  alcanzarían {tope} fotos: {n}/{len(porEspecie)} especies")
porEspecie.nsmallest(10, "fotos_estimadas")

  alcanzarían 200 fotos: 100/100 especies
  alcanzarían 350 fotos: 94/100 especies
  alcanzarían 500 fotos: 90/100 especies

                      fotos  observaciones  obs_disponibles  fotos_estimadas
especie
epargyreus_cruza        287            158              158            287.0
eueides_procula         304            191              195            310.0
mesosemia_mevania       315            186              189            320.0
actinote_neleus         329            203              204            331.0
caligo_eurilochus       332            211              213            335.0
taygetis_mermeria       338            256              256            338.0
battus_ingenuus         350            213              231            380.0
corra_coryna            350            218              257            413.0
euptychoides_laccine    350            241              285            414.0
mysoria_barcastus       350            201              254            442.0